site_name: CODAQUI.dev
site_author: codaqui // endersonmenezes
site_url: https://codaqui.dev/
site_description: "Queremos democratizar o aprendizado tecnológico, e aproximar novas gerações do conteúdo tecnico."
copyright: Codaqui &copy; Copyright - 2022 - Todos os direitos reservados - CNPJ 44.593.429/0001-05
repo_url: https://github.com/codaqui
edit_uri: 'https://github.com/codaqui/institucional/tree/main/docs'

nav:
    - Inicio: index.md
    - Sobre:
      - Equipe: team.md
      - Associação: ong.md
      - Código de Conduta: conduta.md
      - Pais e Responsáveis: pais_responsaveis.md
      - Projetos: projetos.md
    - Participe: #
      - "#QueroEstudar": quero/estudar.md
      - "#QueroApoiar": quero/apoiar.md
    - Trilhas: #
      - GitHub Start: trilhas/github-starter.md
      - Python: trilhas/python.md
      - Javascript: trilhas/javascript.md
    - Blog: blog/index.md
    - Contato: contact.md

theme:
  name: material
  custom_dir: overrides
  language: pt
  logo: assets/logo_blk.png
  palette:
    primary: black
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
  - search
  - meta
  - tags
  - social
  # - git-authors
  - blog:
      post_url_date_format: YYYY/MM/dd
      post_slugify: !!python/name:pymdownx.slugs.uslugify
      archive_name: Arquivo
      categories_name: Categorias
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
  - git-committers:
      repository: codaqui/institucional
      token: !ENV GH_TOKEN
      branch: main
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/codaqui
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/codaquidev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/codaqui
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/codaqui.dev
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCUySP8FaPF_IkM48zmwJr0A
  consent:
    title: LGPD Cookies
    description: >- 
      Usamos cookies para reconhecer suas visitas e preferências repetidas, bem como
      para medir a eficácia de nossa documentação e se os usuários encontrarem o que eles estão procurando. Com o seu consentimento, você está nos ajudando a
      tornar nossa documentação melhor.
