site_name: CODAQUI.dev
site_author: codaqui // endersonmenezes
site_url: https://codaqui.dev/
site_description: "Queremos democratizar o aprendizado tecnológico, e aproximar novas gerações do conteúdo tecnico."
copyright: Codaqui &copy; Copyright - 2022 - Todos os direitos reservados - CNPJ 44.593.429/0001-05
repo_url: https://github.com/codaqui
edit_uri: 'https://github.com/codaqui/institucional/tree/main/docs'

nav:
    - Inicio: index.md
    - Sobre: about.md
    - Projetos: projetos.md
    - Pais e Responsáveis: pais_responsaveis.md
    - Quero: #
      - Estudar: quero/estudar.md
      - Apoiar: quero/apoiar.md
    - Trilhas: #
      - GitHub Start: trilhas/github-starter.md
      - Python: trilhas/python.md
      - Javascript: trilhas/javascript.md
    - Associação: ong.md
    - Social: blog.md
    - Contato: contact.md
    - Código de Conduta: conduta.md

theme:
  name: material
  custom_dir: overrides
  language: pt
  logo: assets/logo_blk.png
  palette:
    primary: black
  favicon: assets/favicon.png
    
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/codaqui
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/codaquidev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/codaqui
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/codaqui.dev
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCUySP8FaPF_IkM48zmwJr0A
