# Copyright (c) 2016-2022 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

blank_issues_enabled: false
contact_links:

  - name: "[CERTIFICADO] Exercício"
    url: https://github.com/codaqui/institucional/issues/new?template=certificado-exercicio.yml&title=%5BCERTIFICADO%5D+%5BEXERCíCIO%5D%3A+
    about: "Desejo criar uma solicitação sobre um certificado existente."


  - name: "[CERTIFICADO] Discussões"
    url: https://github.com/codaqui/institucional/discussions/categories/certificados
    about: "Inicie a proposta de um novo certificado, ou uma discussão sobre um certificado existente."

  - name: "[TRILHA] Sugestão"
    url: https://github.com/codaqui/institucional/issues/new?template=trilha-topico.yml&title=[TRILHA]%20[SUGEST%C3%83O]
    about: Desejo criar uma sugestão para uma trilha já existente.

  - name: "[TRILHA] Discussões"
    url: https://github.com/codaqui/institucional/discussions/categories/trilhas-de-ensino
    about: "Inicie a proposta de uma nova trilha, ou uma discussão sobre uma existente."

  - name: "[CODAQUI] Outros"
    url: https://github.com/codaqui/institucional/discussions/categories/geral
    about: "Inicie uma discussão sobre um assunto não citado nessa página."