name: "[TRILHA] Sugestão"
title: "[TRILHA] [SUGESTÃO]: "
description: "Desejo criar uma sugestão para uma trilha já existente."
assignees:
  - endersonmenezes
body:
  
  - type: checkboxes
    attributes:
      label: Código de Conduta
      description: Por favor leia o Código de Conduta e confirme que você concorda com ele.
      options:
        - label: Eu já li o [Código de Conduta](https://www.codaqui.dev/conduta/) e concordo com ele.
          required: true
  
  - type: dropdown
    attributes:
      label: Eu desejo solicitar...
      description: Selecione o tipo de solicitação que você deseja fazer.
      options:
        - ... uma correção em uma trilha existente.
        - ... um novo tópico para uma trilha existente.

  - type: textarea
    attributes:
      label: Descrição
      description: Forneça uma descrição detalhada do que você deseja.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Tópico
      description: Força o texto do tópico que você deseja seguindo os padrões atuais da trilha.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Obrigado por nos ajudar a melhorar a Codaqui!