endersonmenezes:
  name: Enderson Menezes
  description: Founder
  avatar: https://avatars.githubusercontent.com/u/11020807?v=4

thaifurforo:
  name: Thainara Furforo
  description: Volunteer
  avatar: https://avatars.githubusercontent.com/u/92865769?v=4